<?php

namespace App\Repository;

use App\Entity\Uf;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * UfRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UfRepository extends BaseRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Uf::class);
    }

    public function findLatest()
    {
        return $this->queryLatest()
            ->getQuery()
            ->getResult();
    }

    public function queryLatest()
    {
        return $this->createQueryBuilder('uf')
            ->orderBy('uf.name', 'asc');
    }
}
