# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'pt_BR'
    title: Maximiza Estoque
    email_from_address: mailer@system.send

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:
            $emailFromAddress: '%email_from_address%'
            $adminTitle: '%title%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Form\RegistrationType:
        tags:
            - { name: form.type, alias: app_user_registration }

    App\Form\ProfileType:
        tags:
            - { name: form.type, alias: app_user_profile }

    App\EventListener\StockSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventListener\CustomerSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventListener\CustomerObservationSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventListener\BillSubscriber:
        tags:
            - { name: doctrine.event_subscriber }